### ISSUE TITLE
[Question] How to use your extension_examples for reinforcement learning?

### ISSUE THREAD

**Issue by sambaPython24** [NVIDIA-Omniverse/orbit#112]
### Question

There are good looking examples, that I find in ```Orbit/_isaac_sim/extension_examples```
and in [documentation examples](https://isaac-orbit.github.io/orbit/source/features/environments.html). 

However, in the RL tutorials, we are working with the classical Isaac Sim Examples, e.g. ```Isaac-Ant-v0```. 

How do I call your environments when using 
```
(orbit) python source/standalone/workflows/rl_games/train.py --task Isaac-Ant-v0 --headless
```

and how do I get a list of environments in [documentation examples](https://isaac-orbit.github.io/orbit/source/features/environments.html) that are already available (some of them seem to be under development)?

In the ```import omni.isaac.orbit_envs```I find:
- "Isaac-Cartpole-v0"
- "Isaac-Ant-v0"
- "Isaac-Humanoid-v0"
- "Isaac-Velocity-Anymal-C-v0"
- "Isaac-Reach-Franka-v0"
- "Isaac-Lift-Franka-v0"

-------

Does anybody have any experiences with this?

**Comment by sambaPython24** [comment]
Does anybody have any experiences with this?

**Comment by Mayankm96** [comment]
Hi,

Sorry for the late response.

We have updated our docs with the latest list of environments. Please check them out here: https://isaac-orbit.github.io/orbit/source/features/environments.html

You can also list all the environments using the following script:

```bash
./orbit.sh -p source/standalone/environments/list_envs.py
```
