### ISSUE TITLE
[Question] How to change the video quality?

### ISSUE THREAD

**Issue by sambaPython24** [NVIDIA-Omniverse/orbit#113]
### Question

We can record videos with ```--video```but how can we change the video quality?

**Comment by sachinkundu** [comment]
Not sure if you are using the [RecordVideo](https://isaac-orbit.github.io/orbit/source/tutorials_envs/02_wrappers.html#wrapper-for-recording-videos) wrapper. It has a video resolution config setting, if that's what you mean by video quality. Haven't tried myself, YMMV.

**Comment by Mayankm96** [comment]
Yes, it can be set from this parameter in the configuration object: https://github.com/NVIDIA-Omniverse/Orbit/blob/main/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/isaac_env_cfg.py#L47-L51

**Comment by Mayankm96** [comment]
Closing this issue due to lack of inactivity. If the issue persists, please feel free to open it again.
