### ISSUE TITLE
When do you plan to update rsl_rl?

### ISSUE THREAD

**Issue by chaofiber** [NVIDIA-Omniverse/Orbit#134]
Hello authors,

Thank you very much for the new release on the devel branch, this new branch has a much higher readability. I am wondering when do you plan to update the new rsl_rl package, since I believe the existing code https://github.com/leggedrobotics/rsl_rl.git is not updated and it reports some errors due to interface changes. Alternatively, it would also be great if you can pinpoint changes that I need to make in the rsl_rl source code, it seems the changes should be minor. Thank you.

Best,

**Comment by Mayankm96** [comment]
Hi,

We have made a [MR](https://github.com/leggedrobotics/rsl_rl/pull/14/) on the RSL-RL repository, which should have the necessary updates. You should be able to install the repo from the source by checking out the appropriate branch there. Let us know if you face any issues.

**Comment by chaofiber** [comment]
Thanks, apart from the function in line 157 of runners/on_policy_runner.py brings up an error, the code works very well. Just commenting out that line is enough to fix the error.

**Comment by Mayankm96** [comment]
We have now merged the devel branch of rsl_rl to main. You can use the release branch v2.0: https://github.com/leggedrobotics/rsl_rl/releases/tag/v2.0.0
