### ISSUE TITLE
[Question] Simulation of tracked robot

### ISSUE THREAD

**Issue by Jianlinlynn** [NVIDIA-Omniverse/Orbit#135]
I am trying to import a tracked robot as shown below in orbit, however I do not find related sources to support that. Now I am trying to using multi wheels to replace it but still would like to see if orbit could support that

![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/133347976/29388c2e-46f4-44c4-ac11-7f7a81bf5f29)

**Comment by Mayankm96** [comment]
Hi, I am not sure if this is feasible in Isaac Sim itself. Can you please ask in the [Isaac Sim forums](https://forums.developer.nvidia.com/c/omniverse/simulation/69) whether the simulator supports track simulation?
