### ISSUE TITLE
[Bug Report] Implicit actuator with joint velocity control in Orbit/devel

### ISSUE THREAD

**Issue by chaofiber** [NVIDIA-Omniverse/Orbit#137]
Hi,
I have been trying to use the implicit actuator with velocity control in the devel branch using my own robot model. I used it in the main branch and it worked pretty well. However, I saw some issues in the devel branch:
1. An bug in line 150 of file *joint_action.py*. it should be *cfg.use_default_offset*
2. When I manually set the target velocity in the *write_data_to_sim* function in *articulation.py*, the robot does not behave as I commanded. I am wondering if this function is tested given the error in point 1?

Thank you in advance.

**Comment by Mayankm96** [comment]
Hi,

We haven't tested the joint action for setting velocity targets. But the demo script `play_ridgeback_franka.py` behaves the same even after the new changes. However, we had noticed earlier in 2022.2.1 that with CPU simulation it works fine, while with GPU it doesn't.

Can you please double-check that?

**Comment by chaofiber** [comment]
Hi,
I switched to CPU simulation but it still doesn't work for me. However, I also tested the script ```play_ridgeback_franka.py``` and it is indeed behaving as desired. Would it be possible there exists some parsing errors due to the code refactoring? Can you test from your side by just sending a few fixed velocity command to the robot and see how it moves?

**Comment by Mayankm96** [comment]
Can you share some information on what actuator models you are using?

**Comment by chaofiber** [comment]
Hi,
About the second point, I was using the implicit actuator model with velocity control. However, the bug disappears when I reinstalled the isaac_sim 2022. Not sure if there is any hidden update from nvidia, but if you encounter similar issues, maybe reinstalling isaac sim could help.

**Comment by Mayankm96** [comment]
Strange. Might have been the Orbit installation wasn't updated. But glad it got fixed for now. Closing the issue.
