### ISSUE TITLE
[Bug Report] Missed comma at setup.py for installing extension

### ISSUE THREAD

**Issue by yunlong-wang-cn** [NVIDIA-Omniverse/Orbit#140]
### Describe the bug

You simply missed a comma at line 29 after the `""setuptools<=66""` in the file `source/extensions/omni.isaac.orbit_envs/setup.py`, it will cause an error when install the orbit extension with `orbit -e`.

**Comment by Mayankm96** [comment]
Good catch. This has already been fixed now in the `devel` branch.

**Comment by yunlong-wang-cn** [comment]
nice
