### ISSUE TITLE
[Bug Report] Training Failure in skrl torch_lift_franka_ppo.py at 50-60k Time Steps

### ISSUE THREAD

**Issue by XInyuSong000** [NVIDIA-Omniverse/orbit#147]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug
Hi
I tried to use the given example of skrl of torch_lift_franka_ppo.py (https://skrl.readthedocs.io/en/latest/_downloads/d1e7f4d58abf8eeb7b4ac11f599eac52/torch_lift_franka_ppo.py) to test the training.

It runs well at the beginning. But when the time step is around 50000 or 60000, the run fails and I encountered an error:

```
ValueError: Expected parameter loc (Tensor of shape (4, 8)) of distribution Normal(loc: torch.Size([4, 8]), scale: torch.Size([4, 8])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
```

### Steps to reproduce

Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Uncommented settings in policycfg and rewardcfg of liftenv, e.g., arm_dof_vel = {"scale": 0.5, "noise": {"name": "uniform", "min": -0.01, "max": 0.01}}.
Modified hyperparameters in torch_lift_franka_ppo.py.
Started training. The error occurred around 50,000 to 60,000 global time steps.
The error seems to originate from the GaussianMixin.act method in torch/gaussian.py.

```
  File "torch_lift_franka_ppo.py", line 55, in act
    return GaussianMixin.act(self, inputs, role)
  File "/home/.local/share/ov/pkg/isaac_sim-2022.2.1/kit/python/lib/python3.7/site-packages/skrl/models/torch/gaussian.py", line 150, in act
    self._g_distribution[role] = Normal(mean_actions, log_std.exp())
  File "/home/.local/share/ov/pkg/isaac_sim-2022.2.1/extscache/omni.pip.torch-1_13_1-0.1.4+104.2.lx64/torch-1-13-1/torch/distributions/normal.py", line 56, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/.local/share/ov/pkg/isaac_sim-2022.2.1/extscache/omni.pip.torch-1_13_1-0.1.4+104.2.lx64/torch-1-13-1/torch/distributions/distribution.py", line 57, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter loc (Tensor of shape (4, 8)) of distribution Normal(loc: torch.Size([4, 8]), scale: torch.Size([4, 8])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
```

### System Info

Describe the characteristic of your environment:

- Commit: 00af35e
- Isaac Sim Version: 2022.2.1
- OS:Ubuntu 20.04
- GPU:RTX 3060 Ti
- CUDA: 12.0
- GPU Driver: 525.147.05
- skrl version: 1.0.0

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by berttggg** [comment]
I am facing the same problem too.

**Comment by XInyuSong000** [comment]
> I am facing the same problem too.

Hello, I addressed this issue by removing `min_lr` from `cfg["learning_rate_scheduler_kwargs"]` . Consequently, I was able to execute the training for 200,000 steps successfully. It appears that the NaN error may have been caused by an excessively high learning rate.

**Comment by Mayankm96** [comment]
This one is a bit hard to debug or catch. usually, it has to do with two things:
1. Reset is going wrong and it is set to an invalid state where everything on GPU just explodes
2. Actions that are being set are so large that the PhysX solver breaks

Case 2 might be happening unless some clipping is handled by the policy (or softmax). Internally, in Orbit, we just do an affine transformation of actions and no saturation of input actions. Some libraries such as RL-Games do the clipping but that's handled with their wrappers.

To debug which one of them it could be, try running the training with the `--cpu` flag. That might help in identifying where the issue is coming from. When running GPU kernels from Python, it sometimes doesn't catch errors in the right places.

**Comment by Mayankm96** [comment]
Haven't seen any activity here for a while. Please reopen the issue or create a new one if the problem persists.

**Comment by Lr-2002** [comment]
I've faced the same problem and found it was caused by the env give nan feedback to the reward
``` python 
env.scene['washer'].data.joint_pos
```
is all of `nan` 
but is there any tutorial to locate the reason causing this ?

**Comment by GracefulMan** [comment]
Encountered the same issue.
![image](https://github.com/user-attachments/assets/b5962524-8df9-4ee6-9912-2dcb81235500)
