### ISSUE TITLE
No articulation schema present for prim

### ISSUE THREAD

**Issue by Jianlinlynn** [NVIDIA-Omniverse/Orbit#152]
I am trying to run a self-design robot based on orbit, a simplified version of the robot is generated on onshape. I import the robot into isaac sim with all joints set well, and I test them all by giving actuators. It looks like the following:
  
![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/133347976/fda22a08-ad27-4a87-a7f8-eef6f02195af)

The code I am using as showing below:
![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/133347976/28685c8d-4184-4a77-86e1-8b38da3dd34c)

I keep having this error: 
![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/133347976/9ac57bf6-5139-40d1-aa5b-267c6dedaed9)

The following would be things I have checked, 
1. DoFs are all set and they work
2. All the names of joints are mentioned in the code
3. the default prim has been attached to the robot

I am very confused about it, and many thanks to any replies!

p.s. the tree of my usd are shown as following:
 
![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/133347976/dbac808a-c223-4405-9a64-047ed2322dd4)

**Comment by Jianlinlynn** [comment]
Many thanks to any replies and happy to discuss more about it!

**Comment by jnzhnd** [comment]
Does your original usd model of the robot (the one that you're referencing as _LOG_ROBOT_USD) actually have an articulation?

**Comment by Jianlinlynn** [comment]
> > Does your original usd model of the robot (the one that you're referencing as _LOG_ROBOT_USD) actually have an articulation?
> 
> Hi, @jnzhnd , may I ask you how can I know if there is an articulation or not? From the list?

![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/133347976/b4e09494-93b5-495e-a0b9-6472de3420bc)
The usd is as showing following, I found no functions to add it, however there is a close one called "articulation inspector" under isaac utils. No idea how to deal with that.

Thanks a lot for the reply!

**Comment by jnzhnd** [comment]
Alright, so basically the root prim of your articulation (the one you've selected in the screenshot above called log (defaultPrim) should have an attribute called "Physics/Articulation Root". You can see this if you import for example a UR10 model into an empty stage using "Isaac Examples>Import Robots>UR10 URDF".

Check the attached screenshot for this (bottom right).

![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/3646033/7c54ed4d-3244-4b95-b869-6d4f5af377bd)

To ad a new articulation (if it's not present), right click onto your log prim, and go to Add>Physics>Articulation Root.

![image](https://github.com/NVIDIA-Omniverse/Orbit/assets/3646033/354727ac-8a97-4c9c-9a74-20930427e3ee)

**Comment by Mayankm96** [comment]
Thanks a lot for helping each other out here. If it solved the issue, please close this issue :)

**Comment by Jianlinlynn** [comment]
Thanks for your notification @Mayankm96 , closed.
