### ISSUE TITLE
Add camera on cassie 

### ISSUE THREAD

**Issue by Caroline-wen** [NVIDIA-Omniverse/orbit#183]
# issue 1: 

I followed the steps in the documentation labeled "orbit" on how to add a camera to a Cassie robot. I performed the steps to add a camera to a Cassie robot as outlined in the documentation. The figure included my modified source code. However, when I ran the Cassie robot with these changes, the robot falls over. The camera, on the other hand, follows the robot's movement and displays correctly. How can I resolve the issue of the Cassie robot falling over?

<img width="1263" alt="image" src="https://github.com/NVIDIA-Omniverse/orbit/assets/53698781/3e8ddbfe-9624-4310-a8bd-c899602821b7">

<img width="1280" alt="image" src="https://github.com/NVIDIA-Omniverse/orbit/assets/53698781/a3f24af6-b9fd-4569-b6f8-181085c29ecf">

<img width="2236" alt="image" src="https://github.com/NVIDIA-Omniverse/orbit/assets/53698781/c05fcc5a-20bb-4205-81b2-45a41884ee33">

# issue2: 
I would like to add a camera to the Cassie reinforcement learning example in Orbit, enabling real-time display of the camera feed while Cassie is in motion. I would appreciate some advice on this matter. Thank you very much.

<img width="1265" alt="image" src="https://github.com/NVIDIA-Omniverse/orbit/assets/53698781/f4a6206c-68cf-4649-a240-17489667341c">

<img width="2081" alt="image" src="https://github.com/NVIDIA-Omniverse/orbit/assets/53698781/b69305e8-4ac7-412c-9a6c-54db067d0b63">

**Comment by Mayankm96** [comment]
Hi, 

Sorry for the late reply! I still didn't get around to adding a USD camera to the Cassie example and checking why it falls.

However, for this particular application, I advise using the [RayCastCamera](https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.sensors.html#omni.isaac.orbit.sensors.RayCasterCamera). This simplifies the ray-cast operation (for depth) to static meshes and performs ray-casting using GPU kernels in Warp. Given enough memory (48GB on RTX A6000), we have been able to use this implementation for the ANYmal robot and simulate 4096 environment instances (4 cameras in each environment) while obtaining around 12,000 FPS.

However, if you need dynamic meshes (i.e. see the legs of the robot while walking), then you would need to use the [Camera](https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.sensors.html#usd-camera) implementation. If you want to run training with headless, you would need to pass an additional `--offscreen_render` flag to the script. This is detailed in the [RL tutorial](https://isaac-orbit.github.io/orbit/source/tutorials/03_envs/run_rl_training.html#headless-execution-with-off-screen-render).

**Comment by hang0610** [comment]
> Hi,
> 
> Sorry for the late reply! I still didn't get around to adding a USD camera to the Cassie example and checking why it falls.
> 
> However, for this particular application, I advise using the [RayCastCamera](https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.sensors.html#omni.isaac.orbit.sensors.RayCasterCamera). This simplifies the ray-cast operation (for depth) to static meshes and performs ray-casting using GPU kernels in Warp. Given enough memory (48GB on RTX A6000), we have been able to use this implementation for the ANYmal robot and simulate 4096 environment instances (4 cameras in each environment) while obtaining around 12,000 FPS.
> 
> However, if you need dynamic meshes (i.e. see the legs of the robot while walking), then you would need to use the [Camera](https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.sensors.html#usd-camera) implementation. If you want to run training with headless, you would need to pass an additional `--offscreen_render` flag to the script. This is detailed in the [RL tutorial](https://isaac-orbit.github.io/orbit/source/tutorials/03_envs/run_rl_training.html#headless-execution-with-off-screen-render).

@Mayankm96 Hi, may I know what is the camera resolution in the setting where you created 4096 environments with 4 RayCastCamera-type cameras in each env, on the 48GB VRAM A6000? Thanks!
