### ISSUE TITLE
ModuleNotFoundError: No module named 'omni.isaac.orbit'

### ISSUE THREAD

**Issue by DaojiePENG** [NVIDIA-Omniverse/orbit#209]
### Question
I followed the [installation guide](https://isaac-orbit.github.io/orbit/source/setup/installation.html) , but finally, I got this error:

'''
(orbit_env37) pdj@pdj:~/orbit/orbit$ python source/standalone/tutorials/00_sim/create_empty.py
Traceback (most recent call last):
  File "source/standalone/tutorials/00_sim/create_empty.py", line 20, in <module>
    from omni.isaac.orbit.app import AppLauncher
ModuleNotFoundError: No module named 'omni.isaac.orbit'
'''
I can launch `Isaac Sim` with no problems. It seems like I haven't done anything about orbit. I am not sure what I have missed.

By the way, during the process, I met error about `toml`: ModuleNotFoundError: No module named 'toml'. Then I didi: `pip3 install toml twisted pymodbus` and went on untill I meet the `omni.isaac.orbit` error. Doing the `orbit -e` command, I notice error during the progress as follows:
![image](https://github.com/NVIDIA-Omniverse/orbit/assets/49547589/c487a771-122e-4841-aa27-7cea49897da5)

**Comment by DaojiePENG** [comment]
I realize this is a problem related to python version for I only used the python3.7.

**Comment by mohamedamr13** [comment]
@DaojiePENG Hi, I have the same problem on python 3.10.13. Are you sure this is an issue with the python version ?

**Comment by Mayankm96** [comment]
Hi @mohamedamr13 ,

Can you re-open the issue and provide more information?

**Comment by mohamedamr13** [comment]
> Hi @mohamedamr13 ,
> 
> Can you re-open the issue and provide more information?

Hi @Mayankm96, this was a simple issue where the extensions where not correctly installed. There was a conflict for the library rl_games with my python and after attempting the reinstall, the import worked right away. Do you still want me to reopen the issue ?

**Comment by mattmazzola** [comment]
Related issues:
#406 #407 #103
