### ISSUE TITLE
How to query the spawned Object's bounding box

### ISSUE THREAD

**Issue by zoctipus** [NVIDIA-Omniverse/orbit#215]
### Question
In manipulation task, it will be extremely helpful is a relative object size can be used in observation or reward function
How do you query the extent, (bounding box) of the object that has spawned through orbit?

**Comment by Mayankm96** [comment]
Hi,

Does this function work for you?
> https://docs.omniverse.nvidia.com/py/isaacsim/source/extensions/omni.isaac.core/docs/index.html?highlight=bbox#omni.isaac.core.utils.bounds.create_bbox_cache
