### ISSUE TITLE
[Question] Changing Rigid Object color

### ISSUE THREAD

**Issue by WillMandil001** [NVIDIA-Omniverse/orbit#222]
Hello All :D

I am currently attempting to do some domain randomization with the object (RigidObject()) - Is there a method for changing the current color of the object during randomizations?

I guess there needs to be a function like: 

```
def set_color(self, color: torch.Tensor, body_ids: Sequence[int] | None = None, env_ids: Sequence[int] | None = None):
        # resolve all indices
        physx_env_ids = env_ids
        if env_ids is None:
            env_ids = slice(None)
            physx_env_ids = self._ALL_INDICES
   
        # set into simulation
        self.body_physx_view.set_colors(self._data.body_state_w[:, :, 10:13], indices=physx_env_ids)
```

But of course this set_colors does not exist and so will not work...

Anyone got a good method or something for how to do this?

Thanks in advance!

**Comment by Mayankm96** [comment]
Ooo nice question. I have been thinking of having this for a while. It isn't as straight-forward since setting "colors" depends on the type of material you have on the asset.

Would it be possible to integrate replicator for this randomization? I know tey do texture randomization for synthetic data generation.
> https://docs.omniverse.nvidia.com/extensions/latest/ext_replicator/randomizer_details.html#randomizing-textures

**Comment by Mayankm96** [comment]
Please check the updates on #186 . We have a working example shared there.

I will close this issue to avoid duplicacy.
