### ISSUE TITLE
[Question] Is there any methods to randomize the shape of spawn of a RigidObject

### ISSUE THREAD

**Issue by RyuuChou17** [NVIDIA-Omniverse/orbit#232]
### Is there any methods to randomize the shape of spawn of a RigidObject

I am using orbit for robot learning. In the scene i create a Cylinder by writing a RigidObjectCfg in the scene cfg like this:
```
    cylinder: CylinderCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/cylinder",
        spawn=sim_utils.CylinderCfg(
            radius=0.03, #todo:randomize [0.01, 0.04]
            height=0.5,
            rigid_props=sim_utils.RigidBodyPropertiesCfg(disable_gravity=True, linear_damping=10, angular_damping=10),
            collision_props=sim_utils.CollisionPropertiesCfg(collision_enabled=True),
            visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(1.0, 1.0, 1.0), metallic=0.2),
            physics_material=sim_utils.RigidBodyMaterialCfg(static_friction=1.0, dynamic_friction=1.0, restitution=0.0),
            activate_contact_sensors=True,
        ),
        init_state=RigidObjectCfg.InitialStateCfg(
            pos=[0.40, 0.0, 0.85],
            rot=[0.707, 0.707, 0.0, 0.0],
        ),
    )
````

I hope to randomize the radius and height at the reset time of the cylinder spwan like functions of the radomization of joint states  in the [document](https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.envs.mdp.html#omni.isaac.orbit.envs.mdp.randomizations.reset_joints_by_offset)

I also checked the `omni.physics.tensors.impl` package to find if there is one way to change the shape of spawn in RigidBodyView but there seems no proper way.

So are there any methods to randomize the shape of spawn?

**Comment by Mayankm96** [comment]
Please check the updates on #186 . We have a working example shared there.

I will close this issue to avoid duplicacy.
