### ISSUE TITLE
[Question] Sensor reset

### ISSUE THREAD

**Issue by samibouziri** [NVIDIA-Omniverse/orbit#234]
### Question

Is there a way to properly reset sensors? What I mean by that is, when resetting the scene with the randomization function `reset_scene_to_default` the rigid bodies and the articulation reset their joints and position but for sensors we have to wait one physics step to reset the position (for forward propagation). Meaning directly after reset, if we take an observation from the sensor, that observation will be wrong.

**Comment by Mayankm96** [comment]
Hi @samibouziri ,

This is a limitation of Omniverse and the underlying physics engine. Please check the discussion in #240 for further clarification.
