### ISSUE TITLE
check_instanceable.py in /source/standalone/tools has issues

### ISSUE THREAD

**Issue by phenomen21** [NVIDIA-Omniverse/orbit#242]
### Describe the bug

In line 106 of the check_instanceable.py script there is an error - line goes as
``
prim_utils.create_prim("/World/envs/env_0/Asset", "Xform", usd_path=os.path.abspath(args_cli.usd_path))
``
but it should be
``
prim_utils.create_prim("/World/envs/env_0/Asset", "Xform", usd_path=os.path.abspath(args_cli.input))
``

### Steps to reproduce

Run check_instanceable.py script with any USD file.

### System Info

Describe the characteristic of your environment:

- Commit: 963f304
- Isaac Sim Version: 2023.1.1-rc .8+2023.1.688.573e0291.tcroot
- OS: Ubuntu 22.04
- GPU: Nvidia A10
- CUDA: 12.0
- GPU Driver: 525.85.05

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

- [ ] check_instanceable.py should work without crashing

**Comment by Mayankm96** [comment]
Thank you for pointing this out. Would you like to send the MR with the fix? :)

**Comment by phenomen21** [comment]
Ok will do
