### ISSUE TITLE
[Question] Where to find the source files for the Isaac-Velocity-Rough-Unitree-Go1 RLTask

### ISSUE THREAD

**Issue by mohamedamr13** [NVIDIA-Omniverse/orbit#243]
### Question

Where to find the source files for the Isaac-Velocity-Rough-Unitree-Go1 RLTask where the rewards, curriculum, et cetera are defined, similar to this [tutorial](https://isaac-orbit.github.io/orbit/source/tutorials/03_envs/create_rl_env.html).

**Comment by Mayankm96** [comment]
It's here: https://github.com/NVIDIA-Omniverse/orbit/tree/main/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/locomotion/velocity/config

**Comment by mohamedamr13** [comment]
@Mayankm96 Thanks a lot!
