### ISSUE TITLE
[Question] Getting 404 on Robot environments, where are the examples ?

### ISSUE THREAD

**Issue by renanmb** [NVIDIA-Omniverse/orbit#244]
Nvidia Orbit documentation features several examples of RL tasks implementations.
https://isaac-orbit.github.io/orbit/source/features/environments.html

However, there is a problem: they are no longer available.

To make matters worse. The information about Actuator Groups and Collision Groups is missing and there is no solid example.

My question is: Where can we find good examples of how to structure our files by grouping and configuring collisions and actuators?

**Comment by Mayankm96** [comment]
Hi, 

Are you using the v0.2 release of Orbit or the latest main? All the environments on the website are there.

Please check the discussion https://github.com/NVIDIA-Omniverse/orbit/discussions/153 on why we moved away from actuator groups.
