### ISSUE TITLE
[Question] About February Features

### ISSUE THREAD

**Issue by a2821952** [NVIDIA-Omniverse/Orbit#27]
### Question

Hello, I like this framework very much, and I am also looking forward to the February function mentioned in the roadmap. May I know when the next version will be updated?

**Comment by Mayankm96** [comment]
Hi @a2821952 ,

Thank you for your interest! Due to conference deadlines and Isaac Sim 2022.2.1 release, the development progress in February has been slower than usual. We hope to spend more resources on it this month and get most of the features in by around mid-March.

**Comment by a2821952** [comment]
Thank you for your answer. I look forward to it！
