### ISSUE TITLE
Using assets from Isaac sim (USD)

### ISSUE THREAD

**Issue by SantiDiazC** [NVIDIA-Omniverse/orbit#289]
Hi!
currently I want to create a simulation with a UR5 robot arm and I have the urdf file so I think I can use the urdf importer.
However, I want to know how to import some of the assets that come with Isaac sim like the robot arms, warehouse etc. 

Thank you in advance!

**Comment by Mayankm96** [comment]
Plase check the how-to guide for this information: https://isaac-orbit.github.io/orbit/source/how-to/index.html
