### ISSUE TITLE
[Bug Report] minor docs: in clone orbit.git - make lower-case

### ISSUE THREAD

**Issue by VladimirFokow** [NVIDIA-Omniverse/orbit#293]
### Describe the bug

In https://isaac-orbit.github.io/orbit/source/setup/installation.html#organizing-the-workspace

in the section "Organizing the workspace", there is:

```
# Option 2: With HTTPS
git clone https://github.com/NVIDIA-Omniverse/Orbit.git
```

`orbit.git` should be lower-case, because

- in git if you select "clone" it's lower-case
- in the instructions right below there is: 

```bash
# enter the cloned repository
cd orbit
```
which is lower-case. It would produce an error if the user has cloned the repo with upper-case and now tried to cd into `orbit`. Linux is case-sensitive.

### System Info

- Commit: e3c40ac
- OS: Ubuntu

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

This task is considered **done** if the link is: `https://github.com/NVIDIA-Omniverse/orbit.git` with lowercase "o"

**Comment by Mayankm96** [comment]
Thanks for pointing this out. It should be fixed now.
