### ISSUE TITLE
[Proposal] Why not have `| dict, **kwargs` in `SimulationContext.__init__`?

### ISSUE THREAD

**Issue by VladimirFokow** [NVIDIA-Omniverse/orbit#307]
### Proposal

In the first [introductory tutorial](https://isaac-orbit.github.io/orbit/source/tutorials/00_sim/create_empty.html#configuring-the-simulation-context), there is this:

```py
# Initialize the simulation context
sim_cfg = SimulationCfg(dt=0.01, substeps=1)
sim = SimulationContext(sim_cfg)
```

Proposal:

```py
# Initialize the simulation context
sim = SimulationContext(dt=0.01, substeps=1)
```

also can be possible:

```py
# Initialize the simulation context
sim = SimulationContext({'dt': 0.01, 'substeps': 1})
```

Currently:

https://github.com/NVIDIA-Omniverse/orbit/blob/83d62e212dde22ebc80f140388417fbca12229ed/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sim/simulation_context.py#L109

<br />

### Advantages of the proposed way:

-  would be easier for beginners to grasp.  
When the beginners are already trying to get started, the current complexity doesn't help.

- if there are only a few parameters we want to set, code will be cleaner (fewer classes used - easier to orient in them)

- similar behavior like with `AppLauncher` -> less confusion. Here is how `AppLauncher` works:
```py
# launch omniverse app
app_launcher = AppLauncher(headless=False)
```

<br />

### Motivation

Simpler API.
Better for beginners.
Cleaner code.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

Either:
- [ ] implemented
- [ ] or explained why it will not be implemented

**Comment by Mayankm96** [comment]
Unfortunately, this won't be worked on.

We converged to the other design since we wanted to stay consistent with our config-based system, which happens everywhere in the codebase. Supporting all these different mechanisms reduces code transparency and adds complexity to maintenance.
