### ISSUE TITLE
[Question] Why is `simulation_app.close()` not in `finally`?

### ISSUE THREAD

**Issue by VladimirFokow** [NVIDIA-Omniverse/orbit#308]
### Question

In the introductory tutorial:

https://github.com/NVIDIA-Omniverse/orbit/blob/83d62e212dde22ebc80f140388417fbca12229ed/source/standalone/tutorials/00_sim/create_empty.py#L57-L61

Currently if `main` raises an exception, then the `simulation_app` won't close, right? Is it okay not to close it?

I thought that the [`finally`](https://stackoverflow.com/a/11552007) structure should always be used when we should close something irrespective of the error. 
[`with`](https://stackoverflow.com/q/1369526) could also be used.

**Comment by pascal-roth** [comment]
We tried different setups here. We accept that `simulation_app` might not be closed at the end to allow for better debugging and to let the debugger stop at the error in the code instead of implementing an `except` for all errors.
