### ISSUE TITLE
[Question] Question about mobile_manipulator.py

### ISSUE THREAD

**Issue by shijiyuanaa** [NVIDIA-Omniverse/Orbit#35]
Should line 102 in mobile_manipulator.py be
```python
self._data.ee_jacobian[:] = jacobians[:, self.ee_body_index - 1, :, self.base_num_dof : self.base_num_dof+self.arm_num_dof]
```
?
The original code is 
```python
self._data.ee_jacobian[:] = jacobians[:, self.ee_body_index - 1, :, self.base_num_dof : self.arm_num_dof]
```
but `self.base_num_dof : self.arm_num_dof` seems wrong

**Comment by Mayankm96** [comment]
Thanks for pointing this out! 

Hopefully, in the summer, we will start writing some more concrete unit tests to make sure issues like these don't pop up. We welcome contributions in this direction :)
