### ISSUE TITLE
[Question] How to fix base link?

### ISSUE THREAD

**Issue by john2choi** [NVIDIA-Omniverse/orbit#365]
Hi, Thank you for the nice work,

Main question: How to fix the base link of robot arm on the ground? 

I am using Techman tm5-900 with Tesollo delto-gripper (DG3F) generated by URDF Importer2usd.
When I imported the robot's URDF, unchecked the "Fix Base Link" button as an import option because It couldn't generate multiple environments (can generate but all robots are fixed to the base link) in RLTaskEnv.

Is there any solution or document that I refer to in python as pose processing? 

Thank you already.

(You can check the situation.)
![q1](https://github.com/NVIDIA-Omniverse/orbit/assets/28641977/127b3622-270b-44e5-8ae0-4977ebe5f50f)

**Comment by Mayankm96** [comment]
>  It couldn't generate multiple environments (can generate but all robots are fixed to the base link) in RLTaskEnv.

Why is this the case? Isn't it what you want?

**Comment by john2choi** [comment]
Hi,

In simulation rendering, setting the robot as a fixed base link means that it becomes fixed to the base frame as you can see below. Therefore, the question was whether there is a way to fix the base link in each environment during the envs post-process.

Thank you for the answer.


![Screencastfrom04-19-2024042244PM-ezgif com-video-to-gif-converter](https://github.com/NVIDIA-Omniverse/orbit/assets/28641977/b22fe1b0-0564-4a10-b20b-df6c2d5f3523)

**Comment by Mayankm96** [comment]
It should be possible to move the robot's base to different origins: https://github.com/NVIDIA-Omniverse/orbit/blob/main/source/standalone/tutorials/02_scene/create_scene.py

**Comment by john2choi** [comment]
Solved with https://github.com/NVIDIA-Omniverse/orbit/pull/367
