### ISSUE TITLE
mini_batch_generator, same indice in different epoch

### ISSUE THREAD

**Issue by swstbecrpgmail** [NVIDIA-Omniverse/orbit#370]
The index generation operation for dataset  is placed outside the loop, resulting that the data slices for each epoch remains the same. Is this a problem, or is this a less-than-ideal implementation?

The code is in /rsl_rl/storage/rollout_storage.py
![b0ee2229268dc8b6c76c83ee0edfcb4](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/cfa2f554-1264-4a6f-96ee-a40b93968e8e)

**Comment by Mayankm96** [comment]
This question does not concern Orbit. Please ask in the RSL-RL repository for the developers/community over there to answer.
