### ISSUE TITLE
Why multiply by dt when calculating the reward?

### ISSUE THREAD

**Issue by swstbecrpgmail** [NVIDIA-Omniverse/orbit#371]
Why multiply by dt when calculating the reward, if I may ask politely?

![奖励计算乘上时间步长](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/b223d603-9967-49bd-8e0e-328cd07c5953)

**Comment by Mayankm96** [comment]
From the documentation: https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.managers.html#reward-manager

> The reward manager multiplies the reward term’s weight with the time-step interval dt of the environment. This is done to ensure that the computed reward terms are balanced with respect to the chosen time-step interval in the environment.

**Comment by swstbecrpgmail** [comment]
> From the documentation: https://isaac-orbit.github.io/orbit/source/api/orbit/omni.isaac.orbit.managers.html#reward-manager
> 
> > The reward manager multiplies the reward term’s weight with the time-step interval dt of the environment. This is done to ensure that the computed reward terms are balanced with respect to the chosen time-step interval in the environment.

Thank you very much! This clears up my confusion.
