### ISSUE TITLE
[Question] Can we train Multi-Agent RL policies in Orbit?

### ISSUE THREAD

**Issue by mohamedamr13** [NVIDIA-Omniverse/orbit#375]
### Question

[Question] Can we train Multi-Agent RL policies in Orbit?

**Comment by Mayankm96** [comment]
Depends. We are working on adding the concept of groups to the rewards and termination managers. This allows supporting multi-agent use cases as well. 

Once that's done, it should be possible to obtain a dictionary of observations, rewards, and terminations from the environment and send a dictionary of actions for each agent.

Interfacing with a library that supports multi-agent training is something that doesn't exist yet. However, depending on the application, you can construct your own RL library wrapper (steps in #235).
