### ISSUE TITLE
[Question] Cylindrical wheels in orbit vs. Isaac Sim

### ISSUE THREAD

**Issue by MaltheT** [NVIDIA-Omniverse/orbit#387]
### Cylindrical wheels in orbit vs. Isaac Sim

Hi,

I'm using the orbit to simulate a robot with cylindrical wheels. I've noticed that the wheels' colliders are rougher than expected, leading to bumpy driving behavior, which does not occur when driving the robot in Isaac Sim. 

I expected the wheels to handle minor surface variations smoothly, but instead, the driving is noticeably bumpy.

Is this a known issue, and could you suggest any adjustments to the collider settings or other workarounds?

Isaac Sim colliders:
![wheel_isaac_sample](https://github.com/NVIDIA-Omniverse/orbit/assets/60431464/a310ec04-eb3b-493f-a7ef-abf0bf2c7ed2)

Orbit colliders:
![wheel_orbit_sample](https://github.com/NVIDIA-Omniverse/orbit/assets/60431464/7f31f8c3-75b2-451f-8b39-57a9598268c8)

Thank you for your assistance!

**Comment by Mayankm96** [comment]
Can you try setting these to True and see if this solves the issue?

> https://github.com/NVIDIA-Omniverse/orbit/blob/main/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sim/simulation_context.py#L133-L137

**Comment by MaltheT** [comment]
Yes that fixed it, thank you!
