### ISSUE TITLE
[Bug Report] Container install failed

### ISSUE THREAD

**Issue by swstbecrpgmail** [NVIDIA-Omniverse/orbit#390]
When I run ./docker/container.sh on Ubuntu 20.04, it reports that:  
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
15.21 nvidia-srl-usd 0.13.0 requires tqdm<5.0.0,>=4.63.0, which is not installed.
15.21 nvidia-srl-usd 0.13.0 requires usd-core<24.00,>=21.11, which is not installed.

Sorry to bother you again, but I truly wonder why it occurs. I would greatly appreciate it if you could help me solve this problem or give some potential solutions.

![image](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/e6baf613-fc2a-4957-add7-412fb5917c72)
![image](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/c9b9a718-0bea-46c5-b999-19f6a44928a1)
![image](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/62a09d59-66f6-4e35-afe6-88d69e440bda)
![image](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/273838cc-2676-4ee6-a3cd-f893f470349e)

**Comment by swstbecrpgmail** [comment]
Additionally, the docker version is 26.1.1, and the docker-compose version is 1.25.0.

**Comment by MuhongGuo** [comment]
The issue can be workaround if I add a step in `Dockerfile.base` to install usd-core. See:

```
# Install usd-core 
RUN ${ORBIT_PATH}/orbit.sh -p -m pip install usd-core==23.11

# installing Orbit dependencies
# use pip caching to avoid reinstalling large packages
RUN --mount=type=cache,target=${DOCKER_USER_HOME}/.cache/pip \
    ${ORBIT_PATH}/orbit.sh --install --extra
```

**Comment by swstbecrpgmail** [comment]
> The issue can be workaround if I add a step in `Dockerfile.base` to install usd-core. See:
> 
> ```
> # Install usd-core 
> RUN ${ORBIT_PATH}/orbit.sh -p -m pip install usd-core==23.11
> 
> # installing Orbit dependencies
> # use pip caching to avoid reinstalling large packages
> RUN --mount=type=cache,target=${DOCKER_USER_HOME}/.cache/pip \
>     ${ORBIT_PATH}/orbit.sh --install --extra
> ```
> 
> cc @Mayankm96

Thank you very much! This really solves some errors for me! But one error relative to robomimic still remains: 
![image](https://github.com/NVIDIA-Omniverse/orbit/assets/153968462/e8e39a1b-5c63-440b-b605-fc6c9ba670dd)
I will true appreciate it if anyone has potential solutions or tell me the possible reasons for this error.

**Comment by MuhongGuo** [comment]
@swstbecrpgmail I think it's a network issue when cloning robomimic. I also had this issue but a retry can resolve it. 

In case you don't need `robomimic` in your project, you can modify `Dockerfile.base` to only install other dependencies: `${ORBIT_PATH}/orbit.sh --install --extra rl_games,rsl_rl,sb3`.

If you do need `robomimic`, you may refer to this [solution](https://stackoverflow.com/a/6849424) and test it with this command in a new terminal: `git clone https://github.com/ARISE-Initiative/robomimic.git`.

**Comment by MuhongGuo** [comment]
@swstbecrpgmail Well it seems like the "usd-core missing" issue doesn't cause any problems for the usages. You may just follow the above suggestions to resolve you docker build problem and this github issue can be kindly closed I think.

**Comment by swstbecrpgmail** [comment]
> @swstbecrpgmail I think it's a network issue when cloning robomimic. I also had this issue but a retry can resolve it.
> 
> In case you don't need `robomimic` in your project, you can modify `Dockerfile.base` to only install other dependencies: `${ORBIT_PATH}/orbit.sh --install --extra rl_games,rsl_rl,sb3`.
> 
> If you do need `robomimic`, you may refer to this [solution](https://stackoverflow.com/a/6849424) and test it with this command in a new terminal: `git clone https://github.com/ARISE-Initiative/robomimic.git`.

I apologize for not being able to respond to you in a timely manner due to being quite busy recently. Based on your reply, I just tested your solution. While I failed to install robomimic, I successfully installed orbit. Thank you again for your response!

Additionally, I couldn't run the demo script correctly in the lastest-version orbit, so I still choose to work on the old version.

Again, Thank you very much!

**Comment by swstbecrpgmail** [comment]
Update! The reason for my installation failure is most likely due to the unstable network (I am a developer from China). If you encounter installation failures similar to the failures mentioned above, just try a few more times.
