### ISSUE TITLE
[Question] Potential installation and training issue in lift environment

### ISSUE THREAD

**Issue by VincentYu68** [NVIDIA-Omniverse/Orbit#5]
Thanks for releasing this, really exciting work! Just wanted to share some issues I encountered when trying it out.

When I tried to install the repo I got an error complaining 'pip' not found at this line: https://github.com/NVIDIA-Omniverse/Orbit/blob/main/orbit.sh#L114. After changing it to use the isaac_sim python binary it did work.

Also, the franka lift env doesn't seem to train (got reward ~13 with rl_games and ~18 with rsl_rl, in both case arm just moved away ignoring the object).

**Comment by Mayankm96** [comment]
Good catch. We assumed that the user already has `python3` and `python3-pip` available globally on their system. Will make the changes accordingly to just use the one from the kit if no issues were faced.

Regarding the lift environment, it seems the reward terms didn't match what we used earlier. So the training is going haywire. We are tuning the environment this week to have some reasonable results from it.
