### ISSUE TITLE
[Question] How to add user custom environment

### ISSUE THREAD

**Issue by PARKBONG** [NVIDIA-Omniverse/Orbit#50]
### Question

Hi, I want to **create some custom environment.** 

for example, I want to upgrade the environment `franka-lift -v0`, changing rigid object and manipulator such as UR10.

**what is the best way?** can you recommend some docs for the custom environment?

thanks!

**Comment by Mayankm96** [comment]
This is now updated in the docs with this commit: 26d76f5a0d0b9f5c00a20bd9f3cc8a483f420bf3

We will add more information about the configuration management system in the coming days but hopefully, the code for that is straight-forward to understand.

Please re-open this issue if something more needs to be clarified about adding environments.
