### ISSUE TITLE
[Proposal] mimic_multiplier in GripperActuatorGroupCfg

### ISSUE THREAD

**Issue by PARKBONG** [NVIDIA-Omniverse/Orbit#51]
the mimic_multiplier is multiplied twice in [gripper_group.py](https://github.com/NVIDIA-Omniverse/Orbit/blob/main/source/extensions/omni.isaac.orbit/omni/isaac/orbit/actuators/group/gripper_group.py#L70)

[first](https://github.com/NVIDIA-Omniverse/Orbit/blob/8d5d021895b98a4d7c9092a7cd2797d634958004/source/extensions/omni.isaac.orbit/omni/isaac/orbit/actuators/group/gripper_group.py#L70), and [second](https://github.com/NVIDIA-Omniverse/Orbit/blob/8d5d021895b98a4d7c9092a7cd2797d634958004/source/extensions/omni.isaac.orbit/omni/isaac/orbit/actuators/group/gripper_group.py#L147)

since I applied gripper mimic in configure file for sb3, 

```
        "robotiq_hand": GripperActuatorGroupCfg(
            dof_names=["bot_joint_0_p", "top_joint_0_p", "bot_joint_1_p", "top_joint_1_p", "bot_joint_2_p", "top_joint_2_p"],
            model_cfg=ImplicitActuatorCfg(velocity_limit=20, torque_limit=1000),
            control_cfg=ActuatorControlCfg(command_types=["p_abs"], stiffness={".*": 400}, damping={".*": 20}),
            mimic_multiplier={"bot_joint_0_p":1, "top_joint_0_p":1, "bot_joint_1_p":1, "top_joint_1_p":-1, "bot_joint_2_p":0, "top_joint_2_p":1},
            # speed=1,
            open_dof_pos=0,
            close_dof_pos=0.785398,
```
mimic multiplier didn't work since `"top_joint_1_p":-1` is multiplied twice, in torch elementwise matmul manner. commenting [second](https://github.com/NVIDIA-Omniverse/Orbit/blob/8d5d021895b98a4d7c9092a7cd2797d634958004/source/extensions/omni.isaac.orbit/omni/isaac/orbit/actuators/group/gripper_group.py#L147), it worked.

**Comment by Mayankm96** [comment]
Thank you for pointing this out! Should be fixed now.
