### ISSUE TITLE
[Question] How can I reduce action space while keeping actuation alive?

### ISSUE THREAD

**Issue by PARKBONG** [NVIDIA-Omniverse/Orbit#56]
Hi,

I'm preparing a simple example to study Orbit. Currently, my robot is made up of a 6-DoF Wrist and a 1-DoF gripper with a mimic.

**Problem**: Policy Network returns 7-DoF currently.
**What I want to do**: I only need 6-DoF action for the wrist, and I want to close the gripper manually on _step_impl.
**Question**: How can I reduce the action space of the policy network, keeping the articulation of the gripper alive?

Thank you for your attention!

Best, 
Bong.

----------------------------------------------------------------------------------------------------------------------------------------

Here are my code snippets for the robot (which is similar to [franka.py](https://github.com/NVIDIA-Omniverse/Orbit/blob/main/source/extensions/omni.isaac.orbit/omni/isaac/orbit/robots/config/franka.py))

**robotiq.py**: please see comments

```python
    actuator_groups={
        "wrist_trans": ActuatorGroupCfg(
            dof_names=["trans_[x,y,z]"],
            model_cfg=ImplicitActuatorCfg(velocity_limit=VELOCITY_LIMIT, torque_limit=TORQUE_LIMIT),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 400.0},
                damping={".*": 20.0},
                dof_pos_offset={
                    "trans_x": 0.0,
                    "trans_y": 0.0,
                    "trans_z": 0.0,
                },
            ),
        ),
        "wrist_rev": ActuatorGroupCfg(
            dof_names=["rev_[x-z]"],
            model_cfg=ImplicitActuatorCfg(velocity_limit=VELOCITY_LIMIT, torque_limit=TORQUE_LIMIT),
            control_cfg=ActuatorControlCfg(
                command_types=["p_abs"],
                stiffness={".*": 400.0},
                damping={".*": 20.0},
                dof_pos_offset={"rev_x": 0, "rev_y": 0, "rev_z": 0.0},
            ),
        ),
        # If I comment on this part, 
        # policy network returns only six action spaces, that's good!
        # However, I cannot control the gripper's end-effector. Please see _step_impl
        "robotiq_hand": GripperActuatorGroupCfg(
            dof_names=["bot_joint_0_p", "top_joint_0_p", "bot_joint_1_p", "top_joint_1_p", "bot_joint_2_p", "top_joint_2_p"],
            model_cfg=ImplicitActuatorCfg(velocity_limit=VELOCITY_LIMIT, torque_limit=TORQUE_LIMIT),
            control_cfg=ActuatorControlCfg(command_types=["p_abs"], stiffness={".*": 400}, damping={".*": 20}),
            mimic_multiplier={"bot_joint_0_p": 1, "top_joint_0_p": -1, "bot_joint_1_p": 1, "top_joint_1_p": -1, "bot_joint_2_p": -1, "top_joint_2_p": 1},
            # speed=1,
            open_dof_pos=0,
            close_dof_pos=0.785398,
        )
    },
```

Below is snippets that are parts of [`lift/lift_env`](https://github.com/NVIDIA-Omniverse/Orbit/blob/main/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L139)

[**_step_impl** ](https://github.com/NVIDIA-Omniverse/Orbit/blob/d6a4bc5d9cb2b92da5635ebc5263878e0d3cd241/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L139) please see my comments!

```python
    def _step_impl(self, actions: torch.Tensor):
        ...
        elif self.cfg.control.control_type == "default":
            self.robot_actions[:] = self.actions     # Without comment in "robotiq.py" -> self.robot_actions.shape is [:,7]
                                                     # With a comment in "robotiq.py" -> self.robot_actions.shape is [:,6]
            # HERE IS MY CODE!!
            # Without comment "robotiq.py",  it works, but there is useless action space[:,-1] on policy returns!
            # With the comment "robotiq.py", I cannot access gripper's robot action!
            if is_ee_close_to_object()
                self.robot_actions[:, -1] = 0 # Without comment "robotiq.py" -> close the gripper
                                              # With the comment "robotiq.py" -> it access the last joint of the wrist.
       ...
```

**Comment by PARKBONG** [comment]
I have no idea if is there a more clear way to change action space through the configuration file, I did somehow change it. 

[lift_env.py](https://github.com/NVIDIA-Omniverse/Orbit/blob/main/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L231)/[_**initialize_views**](https://github.com/NVIDIA-Omniverse/Orbit/blob/d6a4bc5d9cb2b92da5635ebc5263878e0d3cd241/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L248)
```
        elif self.cfg.control.control_type == "default":
            # self.num_actions = self.robot.num_actions   # original
            self.num_actions = self.robot.num_actions - 1 # bong
```

[lift_env.py](https://github.com/NVIDIA-Omniverse/Orbit/blob/main/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L231)/**[_step_impl](https://github.com/NVIDIA-Omniverse/Orbit/blob/d6a4bc5d9cb2b92da5635ebc5263878e0d3cd241/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L158)**
```
        elif self.cfg.control.control_type == "default":
            # self.robot_actions[:] = self.actions   # original
            self.robot_actions[:, :-1] = self.actions # bong
```

**Comment by Mayankm96** [comment]
I see what you are trying to do. I think your current workaround is the best way to do it at the moment. To make the code least disrupted, I would suggest renaming the control type to be called something else ("only_arm" or something). That way you can switch in the future easily.

It is a bit hard to capture all the possible use-cases from the config file without letting it blow up. But I agree, there should be a way to specify which "actuator groups" are part of the robot's action space. I will have to think about it but this will require some more restructuring.

**Comment by PARKBONG** [comment]
ok, thank you for your reply!
