### ISSUE TITLE
[Proposal] Gamepad support as teleoperation device

### ISSUE THREAD

**Issue by yangcyself** [NVIDIA-Omniverse/Orbit#71]
### Proposal

I propose adding the gamepad as a device for teleoperation.

### Motivation

A gamepad will make it easier for the teleoperation of the robot arms than the keyboard. Supporting the gamepad also makes the feature set more comprehensive.

### Pitch

Implementations of `gamepad` in `source/extensions/omni.isaac.orbit/omni/isaac/orbit/devices/gamepad`, providing classes such as `Se2Gamepad` and `Se3Gamepad`.

### Alternatives

No

### Additional context

Gamepad has already been used for camera navigation. So users need to unselect the "Gamepad Camera Control" option in the GUI before using it for teleoperation.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Mayankm96** [comment]
Good point. Maybe we can use the Gampepad Manipulation from Omniverse?

Some useful pointers for this:

* https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/ext_omni_isaac_gamepad.html
* https://docs.omniverse.nvidia.com/prod_kit/prod_kit/programmer_ref/input-devices/gamepad.html

**Comment by yangcyself** [comment]
Yes, I already tried. I'm creating a draft PR.

**Comment by Mayankm96** [comment]
Awesome! Looking forward to it :)
