### ISSUE TITLE
[Proposal] Replace certain uses of 'headless' with new flag

### ISSUE THREAD

**Issue by AutonomousHansen** [NVIDIA-Omniverse/Orbit#84]
### Proposal
Currently in certain [demo scripts](https://github.com/NVIDIA-Omniverse/Orbit/blame/ce8c1c015f187790ed6e894cf66bbb26abc13cb7/source/standalone/demo/play_ik_control.py#L218) there are uses of 'headless' to indicate whether or not rendering should be enabled for the SimulationContext.

 I think this could be confusing, because 'headless' already has a potentially conflicting meaning within SimulationApp. A user may input 'headless' to one of these scripts and still want rendering. For instance, one might want to run headlessly on a remote server, and to run the Omniverse Streaming Client for a local GUI.

### Pitch
I think this could be resolved by simply adding another flag 'render' (or alternatively 'no-render') which will take the place of 'headless' in these evaluations and allow it to retain its pure meaning in the SimulationApp API.
 
### Alternatives
We could keep the existing coercion of headless, but it wouldn't work for people hoping to stream.

### Checklist
- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Mayankm96** [comment]
Closing this issue as it is now resolved. We would be updating the `main` with other features from the internal developments soon.
