### ISSUE TITLE
[Bug Report] Inaccurate 'is_success' Condition Testing in lift_env.py

### ISSUE THREAD

**Issue by yangcyself** [NVIDIA-Omniverse/orbit#86]
### Describe the bug

In the [line](https://github.com/NVIDIA-Omniverse/Orbit/blob/ce8c1c015f187790ed6e894cf66bbb26abc13cb7/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_env.py#L186) , the code checks if the object_position_error is less than 0.02 to determine if the task is a success. However, if the object_position_error is not less than 0.02, the task can still be marked as a success if reset_buf is set to 1 (which might happen due to the time limit being reached).

```python
self.extras["is_success"] = torch.where(object_position_error < 0.02, 1, self.reset_buf)
```

To ensure that the task is only marked as a success when the `object_position_error` is less than 0.02, I propose changing the above line to:

```python
self.extras["is_success"] = torch.where(object_position_error < 0.02, 1, 0)
```

In this way, the success condition will solely depend on the object_position_error, which seems to be the intended behavior.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Can you send the PR with this fix and check the training still works? Thanks!
