### ISSUE TITLE
[Question] Quadrupedal locomotion on deformable terrain

### ISSUE THREAD

**Issue by COST-97** [NVIDIA-Omniverse/Orbit#90]
### Question

In the current or future versions, are various deformable and soft terrains supported for quadruped robot locomotion tasks?
Similar to this paper [Learning quadrupedal locomotion on deformable terrain](https://www.science.org/doi/10.1126/scirobotics.ade2256).

**Comment by Mayankm96** [comment]
We don't have this in our internal development plans. However, if you are interested in working on this topic, we can definitely see how we can assist.
