### ISSUE TITLE
[Proposal] Changing installation instructions

### ISSUE THREAD

**Issue by dennisushi** [NVIDIA-Omniverse/orbit#93]
### Proposal

Install before testing installation in [documentation](https://isaac-orbit.github.io/orbit/source/setup/installation.html#installing-orbit)

### Motivation

The installation instructions ask the user to test `python -c "import omni.isaac.orbit; print('Orbit configuration is now complete.')"` before installing with `./orbit.sh --install`, which will fail with `ModuleNotFoundError: No module named 'omni.isaac.orbit'`. 

### Pitch

The order should be swapped?

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Mayankm96** [comment]
Ah yes. That makes sense. Will fix this up in the documentation.
