### ISSUE TITLE
[Bug Report] Bug in code example of API reference: omni.isaac.orbit.actuators.group

### ISSUE THREAD

**Issue by kumar-sanjeeev** [NVIDIA-Omniverse/orbit#95]
### Describe the bug

If you try to follow the example demonstrating the usage of the default actuator group to control the robot with position and velocity commands, the given code snippet is throwing an error in the following parts:

- In the import statements.
- In the resetting of the group command `[group.reset()]`.
- In the `apply_actions()` method

### Steps to reproduce
Include the given code snippet in  `play_arms.py` script in the` orbit/source/standalone/demo` directory after line 104.

### System Info

Describe the characteristic of your environment:

- Isaac Sim Version: [2022.2.1]
- OS: [ Ubuntu 20.04]
- GPU: [ RTX A300]
- CUDA: [11.7]
- GPU Driver: [515.105.01]
### Additional context 
Bug Fix suggestions:

```python

# -- to fix import bug
# given
from omni.isaac.orbit.actuator.model import IdealActuatorCfg
from omni.isaac.orbit.actuator.group import ActuatorControlCfg, ActuatorGroupCfg, ActuatorGroup

# correct: working
from omni.isaac.orbit.actuators.model import IdealActuatorCfg
from omni.isaac.orbit.actuators.group import ActuatorControlCfg, ActuatorGroupCfg, ActuatorGroup

# -- to fix goup.reset()
# provide env_ids

# -- to fix apply_actions()
# given
# set actions into simulator
articulation_view.apply_actions(joint_actions)

# correct : working
articulation_view.apply_action(joint_actions)

```

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Hi, thanks for pointing this out.

Since the repository has undergone large changes, I believe the issue is no longer relevant. Please feel free to bring it up, if the issue persists.
