### ISSUE TITLE
[Bug Report] Error in running any script from Orbit

### ISSUE THREAD

**Issue by kumar-sanjeeev** [NVIDIA-Omniverse/Orbit#98]
### Describe the bug
I tried to run the script from the demo section, and I am getting the following error. Is this error only on my system, or are others also facing a similar one ?

### Steps to reproduce

run this script `./orbit.sh -p source/standalone/demo/play_empty.py`
```
[0.275s] [ext: omni.stats-0.0.0] startup
[0.322s] [ext: omni.rtx.shadercache-1.0.0] startup
[0.333s] [ext: omni.assets.plugins-0.0.0] startup
[0.336s] [ext: omni.gpu_foundation-0.0.0] startup
[0.349s] [ext: carb.windowing.plugins-1.0.0] startup
[0.366s] [ext: omni.kit.renderer.init-0.0.0] startup
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

libGL error: failed to open /dev/dri/card0: Permission denied
libGL error: failed to open /dev/dri/card0: Permission denied
libGL error: failed to load driver: iris
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  243
  Current serial number in output stream:  243
There was an error running python
```
### System Info

Describe the characteristic of your environment:
- Isaac Sim Version: [2022.2.1]
- OS: [ Ubuntu 20.04]
- GPU: [ RTX A300]
- CUDA: [11.7]
- GPU Driver: [515.105.01]

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [ ]  I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by kumar-sanjeeev** [comment]
closing, its problem with my system.

**Comment by BolunDai0216** [comment]
@kumar-sanjeeev I am getting the same issue, would it be possible to share your fix?
